# Copyright (C) 2017 NVIDIA Corporation.  All rights reserved.
# Licensed under the CC BY-NC-ND 4.0 license (https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode).
train:
  snapshot_save_iterations: 100 # How often do you want to save trained models
  image_save_iterations: 100 # How often do you want to save output images during training
  image_display_iterations: 100
  display: 1 # How often do you want to log the training stats
  snapshot_prefix: /media/data2/doronsobol/UNIT/output/unit/attention_breakout2pong/attention_breakout2pong_xy_dual_1/attention_breakout2pong_v0  # Where do you want to save the outputs
  hyperparameters:
    trainer: COCOGANGAMESDUALTrainer
    lr: 0.0001             # learning rate
    ll_direct_link_w: 100  # weight on the self L1 reconstruction loss
    kl_direct_link_w: 0.1 # weight on VAE encoding loss
    ll_cycle_link_w: 100   # weight on the cycle L1 reconstruction loss
    kl_cycle_link_w: 0.1  # weight on the cycle L1 reconstruction loss
    gan_w: 10              # weight on the adversarial loss
    batch_size: 1          # image batch size per domain
    max_iterations: 500000 # maximum number of training epochs
    gen:
      name: COCOResGen
      ch: 64               # base channel number per layer
      input_dim_a: 3
      input_dim_b: 3
      n_enc_front_blk: 3
      n_enc_res_blk: 3
      n_enc_shared_blk: 1
      n_gen_shared_blk: 1
      n_gen_res_blk: 3
      n_gen_front_blk: 3
      use_xy: 1
    dis:
      name: COCODis
      ch: 64
      input_dim_a: 6
      input_dim_b: 6
      n_layer: 6
  datasets:
    train_a: # Domain 1 dataset
      random_crop: 0
      random_flip: 0
      orig_gray: 0
      channels: 3       # image channel number
      scale: 1       # scaling factor for scaling image before processing
      crop_image_height: 256 # crop image size
      crop_image_width: 256  # crop image size
      rotation: 0
      class_name: dataset_image_pairs        # dataset class name
      root: ../datasets/games/attention_breakout/      # dataset folder location
      folder: ./
      list_name: list_breakout.txt  # image list
    train_b: # Domain 2 dataset
      random_crop: 0
      random_flip: 0
      orig_gray: 0
      channels: 3       # image channel number
      scale: 1        # scaling factor for scaling image before processing
      crop_image_height: 256 # crop image size
      crop_image_width: 256  # crop image size
      rotation: 270
      class_name: dataset_image_pairs
      root: ../datasets/games/attention_pong/
      folder: ./
      list_name: list_pong.txt
